name: Build

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        rid:
          [
            linux-x64,
            linux-arm64,
            osx-arm64,
            osx-x64,
            win-arm64,
            win-x64,
            win-x86,
          ]
        include:
          - { os: ubuntu-latest, rid: linux-x64 }
          - { os: ubuntu-latest, rid: linux-arm64 }
          - { os: macos-latest, rid: osx-arm64 }
          - { os: macos-latest, rid: osx-x64 }
          - { os: windows-latest, rid: win-arm64 }
          - { os: windows-latest, rid: win-x64 }
          - { os: windows-latest, rid: win-x86 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
          fetch-depth: 0

      - name: Install .NET Sdk
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Do pack
        run: |
          dotnet pack -p:RuntimeIdentifier=${{ matrix.rid }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: "nupkgs"
