name: Build-Native

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      matrix:
        rid: [ linux-arm64, linux-x64, win-x64, win-x86, win-arm64 , osx-x64, osx-arm64 ]
        include:
          - { rid: linux-arm64, os: ubuntu-latest }
          - { rid: linux-x64, os: ubuntu-latest }
          - { rid: osx-x64, os: macos-latest }
          - { rid: osx-arm64, os: macos-latest }
          - { rid: win-x64, os: windows-latest, cross-arch: x64 }
          - { rid: win-x86, os: windows-latest, cross-arch: amd64_x86 }
          - { rid: win-arm64, os: windows-latest, cross-arch: amd64_arm64 }
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install ninja
        run: pip3 install ninja

      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          arch: ${{ matrix.cross-arch }}
      
      - name: Build tree-sitter
        run: |
          ./build-native.ps1 -RID ${{ matrix.rid }}
        shell: pwsh